spring.application.name=spring_boot_app
spring.datasource.url=jdbc:mysql://localhost:3306/indentity_service
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.servlet.context-path=/identity

jwt.signerKey = a094773a3a33163fd0692d4abc35e08358fae78c2156300411a3218eb3f065c5
