spring.application.name=spring_boot_app
spring.datasource.url=${DBMS_URL:jdbc:mysql://localhost:3306/spring_boot_app}
spring.datasource.username=${DBMS_USERNAME:root}
spring.datasource.password=${DBMS_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.servlet.context-path=/identity
spring.profiles.active=${spring.profiles.active}

jwt.signerKey = ${JWT_SIGNERKEY}
jwt.valid_duration = 3600
jwt.refreshable_duration = 360000